### ISSUE TITLE
Remove blank line after every output line in long listing view

### ISSUE THREAD

**Issue by Brixy** [mike-ward/lsv#1]
Thank you for lsv and congrats! It's nice to see such a feature rich ls alternative in V.

As a V user I switched to lsv from eza and noticed a small glitch:

`lsv -l` draws a blank line after every "output line" if at least one line is longer than the number of columns in you terminal emulator.

This seems to be caused by the trailing spaces drawn after every output line (except the longest line).

**Comment by mike-ward** [comment]
Can you provide a screen shot?

**Comment by Brixy** [comment]
Of course. Here's 3 screen shots.

- terminal wide enough
- terminal too narrow
- terminal too narrow, using the `-B` flag

Tested in foot and kitty.

![1](https://github.com/mike-ward/lsv/assets/1643010/328d2254-7f58-4fe4-bea9-874abfd78b83)

---

![2](https://github.com/mike-ward/lsv/assets/1643010/8ded3226-3c25-42b8-8e7a-6c529f602ca4)

---

![3](https://github.com/mike-ward/lsv/assets/1643010/31dc63d9-c2c8-46ec-b5e0-5fb374155c88)

**Comment by mike-ward** [comment]
Looks like when there are no borders I need to trim the line.  The extra spaces are added in case borders are specified. Obviously, when there are no borders, the extra spaces cause issues. Good find!
 
I think the third option is correct.

**Comment by Brixy** [comment]
Yes, this makes sense. Thanks!

---

For the case concerning the borders I have an idea. But this is not part of this issue, rather an enhancement, if this makes sense to you:

`bat` for example prints borders with the length of the number of columns of the terminal window. It becomes obvious when you increase the width of the window after printing file contents.

The case of a table in lsv is more complex. But it could be possible to achieve something similar if borders -- including pipes -- are truncated, if a line is longer than the number of columns.

![bat1](https://github.com/mike-ward/lsv/assets/1643010/1a9cd446-060b-4797-91e0-ca7745ed93cd)

![bat2](https://github.com/mike-ward/lsv/assets/1643010/65b8d443-f81d-45fb-b07f-a3435cabd37c)

**Comment by Brixy** [comment]
Wow. Your recent fixes and enhancements work perfectly. Thanks a lot.
